<h3 style="text-align: center; background-color: #5AA647; color: white; padding: 8px; border-radius: 6px;">
NLP - Topic Modelling using TF-IDF Vectorizer
</h3

<div style="
    border:2px solid #4CAF50;
    padding:20px;
    border-radius:10px;
    width:550px;
    background-color:#f9f9f9;
    font-family:Arial;
">

<h2 style="margin-top:0;">📊 Topic Modeling — Simple Explanation</h2>

<p>
Topic modeling is a way for computers to automatically find hidden topics in a collection of text documents.
</p>

<p>
👉 <strong>In very simple terms:</strong><br>
It answers the question — 
<em>What are the main themes in this text data?</em>
</p>

<h3>✅ Example</h3>

<p>Imagine you have 1000 customer reviews.</p>

<ul>
    <li>🧾 Delivery Issues → late, delay, shipping</li>
    <li>📦 Product Quality → broken, good, durable</li>
    <li>💬 Customer Service → support, response, help</li>
</ul>

<p>
👉 Even though the reviews are mixed, the model <strong>discovers patterns automatically.</strong>
</p>

<h3>🧠 How it works (basic idea)</h3>
<ul>
    <li>Reads all text documents</li>
    <li>Looks for frequently occurring words together</li>
    <li>Groups related words into topics</li>
</ul>

<h3>⚙️ Common Algorithms</h3>
<ul>
    <li>LDA (Latent Dirichlet Allocation) → most common</li>
    <li>NMF (Non-negative Matrix Factorization) → easy and fast</li>
</ul>

<h3>✅ Output Example</h3>

<p><strong>Topic 1:</strong> [delivery, delay, shipping, late]</p>
<p><strong>Topic 2:</strong> [quality, product, good, bad]</p>

<p>
👉 You interpret these as:
</p>
<ul>
    <li><strong>Topic 1 → Delivery</strong></li>
    <li><strong>Topic 2 → Product Quality</strong></li>
</ul>

<h3>📌 Where it is used</h3>
<ul>
    <li>Customer feedback analysis</li>
    <li>Chat/message clustering</li>
    <li>News article grouping</li>
    <li>Recommendation systems</li>
</ul>

<h3>🧾 One-line Summary</h3>
<p>
👉 <strong>Topic modeling finds hidden themes in large text data automatically.</strong>
</p>

</div>

In [1]:
import pandas as pd
df = pd.read_csv("mabel.txt",header=None,encoding='utf8', on_bad_lines='skip')

In [2]:
# Remove the first row (often unwanted header or metadata row)
df = df.drop(0)

# Rename the columns to 'Date' and 'Chat'
df.columns = ['Date', 'Chat']

# Split the 'Chat' column into two parts using '-' as separator
# n=1 ensures only the first '-' is used for splitting
# expand=True creates separate columns
Message = df["Chat"].str.split("-", n=1, expand=True)

# Assign the first part of the split to a new column 'Time'
df["Time"] = Message[0]

# Now split the second part again using ':' to separate Name and message text
Message1 = Message[1].str.split(":", n=1, expand=True)

# Assign the first part as 'Name' (person who sent the message)
df["Name"] = Message1[0]

# Assign the second part as the actual chat message
df["Chat"] = Message1[1]

# Reorder/select only the required columns in the desired order
df = df[["Date", "Time", "Name", "Chat"]]

# Display the final cleaned DataFrame
df

,Date,Time,Name,Chat
1,05/12/19,1:42 pm,Mabel Infoziant,Hi this is Mabel we just spoke
2,05/12/19,1:42 pm,Mabel Infoziant,What’s your full name
3,05/12/19,1:42 pm,AR❤,Ramisha Rani K
4,05/12/19,1:42 pm,Mabel Infoziant,Ok
5,05/12/19,1:42 pm,Mabel Infoziant,ramisharanik@gmail.com
6,05/12/19,1:43 pm,Mabel Infoziant,Your email Id?
7,05/12/19,1:43 pm,AR❤,Yes Mam
8,05/12/19,1:43 pm,Mabel Infoziant,I will send 2 abstracts for u to start working
9,05/12/19,1:43 pm,AR❤,Yeah mam
10,05/12/19,1:43 pm,Mabel Infoziant,Give me the list that u have too
11,05/12/19,1:43 pm,Mabel Infoziant,Send me cbe office address and phone number I...
12,05/12/19,1:44 pm,AR❤,Yeah Mam within Evening I will forward you mam.
13,05/12/19,1:45 pm,AR❤,Tomorrow I have to visit the office.yet not I...
14,05/12/19,1:48 pm,Mabel Infoziant,ok
15,05/12/19,1:48 pm,Mabel Infoziant,send the details of office location once u ge...
16,05/12/19,1:49 pm,AR❤,Sure mam. Soon I will share details with you mam
17,05/12/19,2:00 pm,AR❤,I have read the Abstract mam. We can do mam. ...
18,05/12/19,2:04 pm,Mabel Infoziant,I think Vignesh has the data set will ask him...
19,05/12/19,2:04 pm,Mabel Infoziant,I have sent the abstracts
20,05/12/19,2:06 pm,AR❤,Ok mam
21,05/12/19,2:07 pm,AR❤,I have read both the abstract mam. We can do ...
22,05/12/19,4:44 pm,Mabel Infoziant,Yes we need to ya about amount and all other ...
23,05/12/19,4:48 pm,AR❤,Sure mam.
24,05/12/19,8:07 pm,AR❤,Shall I call mam?
25,08/12/19,10:45 pm,Mabel Infoziant,Hi I was at church couldn’t take your call
26,08/12/19,11:52 pm,AR❤,It's k mam
27,08/12/19,11:55 pm,AR❤,Just to know the tomorrow plan mam.will see t...
28,09/12/19,12:09 pm,AR❤,Mam can u send Vignesh number??
29,09/12/19,12:13 pm,Mabel Infoziant,Vignesh ML Infoziant.vcf (file attached)
30,09/12/19,12:23 pm,Mabel Infoziant,I was in a meeting sorry
31,09/12/19,12:25 pm,AR❤,Can I cal u mam
32,09/12/19,12:26 pm,AR❤,Waiting for u r finalization of rates for our...
33,09/12/19,12:26 pm,AR❤,If we finiliaze I can work with full involvem...
34,09/12/19,12:28 pm,AR❤,So what ever may be ..if you think your are c...
35,09/12/19,12:28 pm,AR❤,You deleted this message
36,09/12/19,12:29 pm,AR❤,Do the needful
37,09/12/19,12:41 pm,Mabel Infoziant,No ma please hold I am in a hot meeting with ...
38,09/12/19,12:42 pm,AR❤,Ok mam thank u
39,10/12/19,7:59 am,Mabel Infoziant,Ramisha we need to talk today i will call u a...
40,10/12/19,8:00 am,Mabel Infoziant,Be ready to discuss about the ML titles u have
41,10/12/19,8:55 am,AR❤,Okay mam
42,12/12/19,2:26 pm,Mabel Infoziant,ok
43,15/12/19,8:22 pm,AR❤,Mam are u free?
44,15/12/19,8:40 pm,Mabel Infoziant,Am at church can call very late or tomorrow only
45,15/12/19,8:40 pm,AR❤,Kk mam. I will ask Arun brother. Small doubt ...
46,18/12/19,3:09 pm,AR❤,Hi mam
47,18/12/19,3:09 pm,AR❤,Any updates mam?
48,18/12/19,3:11 pm,Mabel Infoziant,U might have to start on the WhatsApp analysis
49,18/12/19,3:11 pm,Mabel Infoziant,There is one project that got committed
50,18/12/19,3:12 pm,AR❤,Kk mam👍🏻

#### TF-IDF VEctorizer Strarts here

In [3]:
# Import TF-IDF Vectorizer to convert text into numerical format
from sklearn.feature_extraction.text import TfidfVectorizer

# Create TF-IDF object
# max_df=0.95 → Ignore words that appear in more than 95% of documents (too common)
# min_df=2 → Ignore words that appear in less than 2 documents (too rare)
# stop_words='english' → Remove common words like "the", "is", "and"
tfidf = TfidfVectorizer(max_df=0.95, min_df=2, stop_words='english')

# Convert the 'Chat' text column into a Document-Term Matrix (DTM)
# Rows = documents (messages), Columns = words, Values = TF-IDF scores
dtm = tfidf.fit_transform(df["Chat"])


# Import NMF model for topic modeling
from sklearn.decomposition import NMF

# Create NMF model
# n_components=5 → Number of topics to extract
# random_state=42 → Ensures reproducible results
nmf_model = NMF(n_components=5, random_state=42)

# Fit the NMF model on the DTM
# The model learns patterns and identifies 5 topics from the text data
nmf_model.fit(dtm)

NMF(n_components=5, random_state=42)

#### Topic Modelling code Changes

In [11]:
# Loop through each topic learned by the NMF model
# enumerate() returns both topic index and topic values
for index, topic in enumerate(nmf_model.components_):
    
    # For each topic:
    # topic contains weights for each word in the vocabulary
    
    # argsort() → sorts indices of words based on their weights
    # [-10:] → selects top 10 words with highest importance in the topic
    # tfidf.get_feature_names() → gets list of words (vocabulary)
    # [i] → picks word using index
    
    results = ([tfidf.get_feature_names_out()[i] for i in topic.argsort()[-10:]])
    
    # Print top 10 words representing the topic
    print(f"Topic {index}: {results}")

Topic 0: ['share', 'soon', 'ask', 'yes', 'sure', 'read', 'abstract', 'kk', 'yeah', 'mam']
Topic 1: ['hi', 'kk', 'know', 'meeting', 'yes', 'just', 'send', 'tomorrow', 'mam', 'ok']
Topic 2: ['details', 'abstracts', 'start', 'students', 'phone', 'ask', 'office', 'number', 'vignesh', 'send']
Topic 3: ['ask', 'abstracts', 'number', 'mam', 'office', 'know', 'just', 'tomorrow', 'church', 'hi']
Topic 4: ['students', 'know', 'sure', 'share', 'soon', 'meeting', 'details', 'yes', 'need', 'ramisha']

#### Add the Topic result in a column to the DataFrame

In [6]:
# Transform the document-term matrix (DTM) into topic space
# Output: Each row = document, each column = topic score
topic_results = nmf_model.transform(dtm)

# Assign the dominant topic to each document
# argmax(axis=1) → finds the index (topic number) with highest score for each row
df["Topic"] = topic_results.argmax(axis=1)

df

,Date,Time,Name,Chat,Topic
1,05/12/19,1:42 pm,Mabel Infoziant,Hi this is Mabel we just spoke,3
2,05/12/19,1:42 pm,Mabel Infoziant,What’s your full name,0
3,05/12/19,1:42 pm,AR❤,Ramisha Rani K,4
4,05/12/19,1:42 pm,Mabel Infoziant,Ok,1
5,05/12/19,1:42 pm,Mabel Infoziant,ramisharanik@gmail.com,0
6,05/12/19,1:43 pm,Mabel Infoziant,Your email Id?,0
7,05/12/19,1:43 pm,AR❤,Yes Mam,4
8,05/12/19,1:43 pm,Mabel Infoziant,I will send 2 abstracts for u to start working,2
9,05/12/19,1:43 pm,AR❤,Yeah mam,0
10,05/12/19,1:43 pm,Mabel Infoziant,Give me the list that u have too,0
11,05/12/19,1:43 pm,Mabel Infoziant,Send me cbe office address and phone number I...,2
12,05/12/19,1:44 pm,AR❤,Yeah Mam within Evening I will forward you mam.,0
13,05/12/19,1:45 pm,AR❤,Tomorrow I have to visit the office.yet not I...,2
14,05/12/19,1:48 pm,Mabel Infoziant,ok,1
15,05/12/19,1:48 pm,Mabel Infoziant,send the details of office location once u ge...,2
16,05/12/19,1:49 pm,AR❤,Sure mam. Soon I will share details with you mam,0
17,05/12/19,2:00 pm,AR❤,I have read the Abstract mam. We can do mam. ...,0
18,05/12/19,2:04 pm,Mabel Infoziant,I think Vignesh has the data set will ask him...,2
19,05/12/19,2:04 pm,Mabel Infoziant,I have sent the abstracts,2
20,05/12/19,2:06 pm,AR❤,Ok mam,1
21,05/12/19,2:07 pm,AR❤,I have read both the abstract mam. We can do ...,0
22,05/12/19,4:44 pm,Mabel Infoziant,Yes we need to ya about amount and all other ...,4
23,05/12/19,4:48 pm,AR❤,Sure mam.,0
24,05/12/19,8:07 pm,AR❤,Shall I call mam?,0
25,08/12/19,10:45 pm,Mabel Infoziant,Hi I was at church couldn’t take your call,3
26,08/12/19,11:52 pm,AR❤,It's k mam,0
27,08/12/19,11:55 pm,AR❤,Just to know the tomorrow plan mam.will see t...,3
28,09/12/19,12:09 pm,AR❤,Mam can u send Vignesh number??,2
29,09/12/19,12:13 pm,Mabel Infoziant,Vignesh ML Infoziant.vcf (file attached),2
30,09/12/19,12:23 pm,Mabel Infoziant,I was in a meeting sorry,4
31,09/12/19,12:25 pm,AR❤,Can I cal u mam,0
32,09/12/19,12:26 pm,AR❤,Waiting for u r finalization of rates for our...,0
33,09/12/19,12:26 pm,AR❤,If we finiliaze I can work with full involvem...,2
34,09/12/19,12:28 pm,AR❤,So what ever may be ..if you think your are c...,0
35,09/12/19,12:28 pm,AR❤,You deleted this message,0
36,09/12/19,12:29 pm,AR❤,Do the needful,0
37,09/12/19,12:41 pm,Mabel Infoziant,No ma please hold I am in a hot meeting with ...,4
38,09/12/19,12:42 pm,AR❤,Ok mam thank u,1
39,10/12/19,7:59 am,Mabel Infoziant,Ramisha we need to talk today i will call u a...,4
40,10/12/19,8:00 am,Mabel Infoziant,Be ready to discuss about the ML titles u have,2
41,10/12/19,8:55 am,AR❤,Okay mam,0
42,12/12/19,2:26 pm,Mabel Infoziant,ok,1
43,15/12/19,8:22 pm,AR❤,Mam are u free?,0
44,15/12/19,8:40 pm,Mabel Infoziant,Am at church can call very late or tomorrow only,3
45,15/12/19,8:40 pm,AR❤,Kk mam. I will ask Arun brother. Small doubt ...,0
46,18/12/19,3:09 pm,AR❤,Hi mam,3
47,18/12/19,3:09 pm,AR❤,Any updates mam?,0
48,18/12/19,3:11 pm,Mabel Infoziant,U might have to start on the WhatsApp analysis,2
49,18/12/19,3:11 pm,Mabel Infoziant,There is one project that got committed,2
50,18/12/19,3:12 pm,AR❤,Kk mam👍🏻,0

In [7]:
df["Topic"].value_counts()

Topic
0    22
2    12
4     6
3     5
1     5
Name: count, dtype: int64

#### Topic Modlelling with Sentiment analysis

In [13]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer

# Create the analyzer object
sid = SentimentIntensityAnalyzer()

# Step 1: Topic Modeling (already done)
df["Topic"] = nmf_model.transform(dtm).argmax(axis=1)

# Step 2: Sentiment Analysis
df["Sentiment"] = df["Chat"].apply(
    lambda x: sid.polarity_scores(x)['compound']
)

# Step 3: Combine (average sentiment per topic)
df.groupby("Topic")["Sentiment"].mean()

Topic
0    0.164482
1    0.351180
2    0.103400
3    0.088080
4    0.071767
Name: Sentiment, dtype: float64

In [14]:
for i, topic in enumerate(nmf_model.components_):
    words = [tfidf.get_feature_names_out()[j] for j in topic.argsort()[-10:]]
    print(f"Topic {i}: {words}")

Topic 0: ['share', 'soon', 'ask', 'yes', 'sure', 'read', 'abstract', 'kk', 'yeah', 'mam']
Topic 1: ['hi', 'kk', 'know', 'meeting', 'yes', 'just', 'send', 'tomorrow', 'mam', 'ok']
Topic 2: ['details', 'abstracts', 'start', 'students', 'phone', 'ask', 'office', 'number', 'vignesh', 'send']
Topic 3: ['ask', 'abstracts', 'number', 'mam', 'office', 'know', 'just', 'tomorrow', 'church', 'hi']
Topic 4: ['students', 'know', 'sure', 'share', 'soon', 'meeting', 'details', 'yes', 'need', 'ramisha']