<h3 style="text-align: center; background-color: #5AA647; color: white; padding: 8px; border-radius: 6px;">
NLP - Topic Modelling using LDA vectorizer
</h3

<div style="
    border:2px solid #4CAF50;
    padding:20px;
    border-radius:10px;
    width:550px;
    background-color:#f9f9f9;
    font-family:Arial;
">

<h2 style="margin-top:0;">📊 Topic Modeling — Simple Explanation</h2>

<p>
Topic modeling is a way for computers to automatically find hidden topics in a collection of text documents.
</p>

<p>
👉 <strong>In very simple terms:</strong><br>
It answers the question — 
<em>What are the main themes in this text data?</em>
</p>

<h3>✅ Example</h3>

<p>Imagine you have 1000 customer reviews.</p>

<ul>
    <li>🧾 Delivery Issues → late, delay, shipping</li>
    <li>📦 Product Quality → broken, good, durable</li>
    <li>💬 Customer Service → support, response, help</li>
</ul>

<p>
👉 Even though the reviews are mixed, the model <strong>discovers patterns automatically.</strong>
</p>

<h3>🧠 How it works (basic idea)</h3>
<ul>
    <li>Reads all text documents</li>
    <li>Looks for frequently occurring words together</li>
    <li>Groups related words into topics</li>
</ul>

<h3>⚙️ Common Algorithms</h3>
<ul>
    <li>LDA (Latent Dirichlet Allocation) → most common</li>
    <li>NMF (Non-negative Matrix Factorization) → easy and fast</li>
</ul>

<h3>✅ Output Example</h3>

<p><strong>Topic 1:</strong> [delivery, delay, shipping, late]</p>
<p><strong>Topic 2:</strong> [quality, product, good, bad]</p>

<p>
👉 You interpret these as:
</p>
<ul>
    <li><strong>Topic 1 → Delivery</strong></li>
    <li><strong>Topic 2 → Product Quality</strong></li>
</ul>

<h3>📌 Where it is used</h3>
<ul>
    <li>Customer feedback analysis</li>
    <li>Chat/message clustering</li>
    <li>News article grouping</li>
    <li>Recommendation systems</li>
</ul>

<h3>🧾 One-line Summary</h3>
<p>
👉 <strong>Topic modeling finds hidden themes in large text data automatically.</strong>
</p>

</div>

In [1]:
import pandas as pd
df = pd.read_csv("mabel.txt",header=None,encoding='utf8', on_bad_lines='skip')

In [2]:
# Remove the first row (often unwanted header or metadata row)
df = df.drop(0)

# Rename the columns to 'Date' and 'Chat'
df.columns = ['Date', 'Chat']

# Split the 'Chat' column into two parts using '-' as separator
# n=1 ensures only the first '-' is used for splitting
# expand=True creates separate columns
Message = df["Chat"].str.split("-", n=1, expand=True)

# Assign the first part of the split to a new column 'Time'
df["Time"] = Message[0]

# Now split the second part again using ':' to separate Name and message text
Message1 = Message[1].str.split(":", n=1, expand=True)

# Assign the first part as 'Name' (person who sent the message)
df["Name"] = Message1[0]

# Assign the second part as the actual chat message
df["Chat"] = Message1[1]

# Reorder/select only the required columns in the desired order
df = df[["Date", "Time", "Name", "Chat"]]

# Display the final cleaned DataFrame
df

,Date,Time,Name,Chat
1,05/12/19,1:42 pm,Mabel Infoziant,Hi this is Mabel we just spoke
2,05/12/19,1:42 pm,Mabel Infoziant,What’s your full name
3,05/12/19,1:42 pm,AR❤,Ramisha Rani K
4,05/12/19,1:42 pm,Mabel Infoziant,Ok
5,05/12/19,1:42 pm,Mabel Infoziant,ramisharanik@gmail.com
6,05/12/19,1:43 pm,Mabel Infoziant,Your email Id?
7,05/12/19,1:43 pm,AR❤,Yes Mam
8,05/12/19,1:43 pm,Mabel Infoziant,I will send 2 abstracts for u to start working
9,05/12/19,1:43 pm,AR❤,Yeah mam
10,05/12/19,1:43 pm,Mabel Infoziant,Give me the list that u have too
11,05/12/19,1:43 pm,Mabel Infoziant,Send me cbe office address and phone number I...
12,05/12/19,1:44 pm,AR❤,Yeah Mam within Evening I will forward you mam.
13,05/12/19,1:45 pm,AR❤,Tomorrow I have to visit the office.yet not I...
14,05/12/19,1:48 pm,Mabel Infoziant,ok
15,05/12/19,1:48 pm,Mabel Infoziant,send the details of office location once u ge...
16,05/12/19,1:49 pm,AR❤,Sure mam. Soon I will share details with you mam
17,05/12/19,2:00 pm,AR❤,I have read the Abstract mam. We can do mam. ...
18,05/12/19,2:04 pm,Mabel Infoziant,I think Vignesh has the data set will ask him...
19,05/12/19,2:04 pm,Mabel Infoziant,I have sent the abstracts
20,05/12/19,2:06 pm,AR❤,Ok mam
21,05/12/19,2:07 pm,AR❤,I have read both the abstract mam. We can do ...
22,05/12/19,4:44 pm,Mabel Infoziant,Yes we need to ya about amount and all other ...
23,05/12/19,4:48 pm,AR❤,Sure mam.
24,05/12/19,8:07 pm,AR❤,Shall I call mam?
25,08/12/19,10:45 pm,Mabel Infoziant,Hi I was at church couldn’t take your call
26,08/12/19,11:52 pm,AR❤,It's k mam
27,08/12/19,11:55 pm,AR❤,Just to know the tomorrow plan mam.will see t...
28,09/12/19,12:09 pm,AR❤,Mam can u send Vignesh number??
29,09/12/19,12:13 pm,Mabel Infoziant,Vignesh ML Infoziant.vcf (file attached)
30,09/12/19,12:23 pm,Mabel Infoziant,I was in a meeting sorry
31,09/12/19,12:25 pm,AR❤,Can I cal u mam
32,09/12/19,12:26 pm,AR❤,Waiting for u r finalization of rates for our...
33,09/12/19,12:26 pm,AR❤,If we finiliaze I can work with full involvem...
34,09/12/19,12:28 pm,AR❤,So what ever may be ..if you think your are c...
35,09/12/19,12:28 pm,AR❤,You deleted this message
36,09/12/19,12:29 pm,AR❤,Do the needful
37,09/12/19,12:41 pm,Mabel Infoziant,No ma please hold I am in a hot meeting with ...
38,09/12/19,12:42 pm,AR❤,Ok mam thank u
39,10/12/19,7:59 am,Mabel Infoziant,Ramisha we need to talk today i will call u a...
40,10/12/19,8:00 am,Mabel Infoziant,Be ready to discuss about the ML titles u have
41,10/12/19,8:55 am,AR❤,Okay mam
42,12/12/19,2:26 pm,Mabel Infoziant,ok
43,15/12/19,8:22 pm,AR❤,Mam are u free?
44,15/12/19,8:40 pm,Mabel Infoziant,Am at church can call very late or tomorrow only
45,15/12/19,8:40 pm,AR❤,Kk mam. I will ask Arun brother. Small doubt ...
46,18/12/19,3:09 pm,AR❤,Hi mam
47,18/12/19,3:09 pm,AR❤,Any updates mam?
48,18/12/19,3:11 pm,Mabel Infoziant,U might have to start on the WhatsApp analysis
49,18/12/19,3:11 pm,Mabel Infoziant,There is one project that got committed
50,18/12/19,3:12 pm,AR❤,Kk mam👍🏻

#### Counter VEctorizer Strarts here

In [3]:
# Import CountVectorizer (IMPORTANT for LDA)
from sklearn.feature_extraction.text import CountVectorizer

# Create count vectorizer
cv = CountVectorizer(
    max_df=0.95,       # ignore very frequent words
    min_df=2,          # ignore rare words
    stop_words='english'
)

# Create Document-Term Matrix (counts, not TF-IDF)
dtm = cv.fit_transform(df["Chat"])

#### LDA code changes

In [4]:
# Import LDA
from sklearn.decomposition import LatentDirichletAllocation

# Create LDA model
lda_model = LatentDirichletAllocation(
    n_components=5,    # number of topics
    random_state=42
)

# Fit model
lda_model.fit(dtm)

LatentDirichletAllocation(n_components=5, random_state=42)

#### Display Topics (Top Words)

In [5]:
# Print top words for each topic
for index, topic in enumerate(lda_model.components_):
    
    results = [cv.get_feature_names_out()[i] for i in topic.argsort()[-10:]]
    
    print(f"Topic {index}: {results}")

Topic 0: ['mam', 'number', 'need', 'ask', 'think', 'yes', 'ml', 'send', 'details', 'vignesh']
Topic 1: ['details', 'ask', 'share', 'phone', 'students', 'office', 'need', 'send', 'number', 'ok']
Topic 2: ['project', 'share', 'soon', 'finiliaze', 'yeah', 'kk', 'sure', 'read', 'abstract', 'mam']
Topic 3: ['finiliaze', 'ramisha', 'hi', 'mam', 'know', 'church', 'project', 'just', 'office', 'tomorrow']
Topic 4: ['mam', 'just', 'send', 'ramisha', 'church', 'soon', 'meeting', 'start', 'abstracts', 'hi']

#### Assign topics to dataframe

In [6]:
# Get topic distribution for each document
topic_results = lda_model.transform(dtm)

# Assign dominant topic
df["Topic"] = topic_results.argmax(axis=1)

#### Add Sentiment

In [7]:

from nltk.sentiment.vader import SentimentIntensityAnalyzer
sid = SentimentIntensityAnalyzer()

df["Sentiment"] = df["Chat"].apply(
    lambda x: sid.polarity_scores(x)['compound']
)

# Topic-wise sentiment
df.groupby("Topic")["Sentiment"].mean()
df

,Date,Time,Name,Chat,Topic,Sentiment
1,05/12/19,1:42 pm,Mabel Infoziant,Hi this is Mabel we just spoke,4,0.0000
2,05/12/19,1:42 pm,Mabel Infoziant,What’s your full name,0,0.0000
3,05/12/19,1:42 pm,AR❤,Ramisha Rani K,4,0.0000
4,05/12/19,1:42 pm,Mabel Infoziant,Ok,1,0.2960
5,05/12/19,1:42 pm,Mabel Infoziant,ramisharanik@gmail.com,0,0.0000
6,05/12/19,1:43 pm,Mabel Infoziant,Your email Id?,0,0.0000
7,05/12/19,1:43 pm,AR❤,Yes Mam,2,0.4019
8,05/12/19,1:43 pm,Mabel Infoziant,I will send 2 abstracts for u to start working,4,0.0000
9,05/12/19,1:43 pm,AR❤,Yeah mam,2,0.2960
10,05/12/19,1:43 pm,Mabel Infoziant,Give me the list that u have too,0,0.0000
11,05/12/19,1:43 pm,Mabel Infoziant,Send me cbe office address and phone number I...,1,0.0772
12,05/12/19,1:44 pm,AR❤,Yeah Mam within Evening I will forward you mam.,2,0.2960
13,05/12/19,1:45 pm,AR❤,Tomorrow I have to visit the office.yet not I...,3,0.0000
14,05/12/19,1:48 pm,Mabel Infoziant,ok,1,0.2960
15,05/12/19,1:48 pm,Mabel Infoziant,send the details of office location once u ge...,1,0.3612
16,05/12/19,1:49 pm,AR❤,Sure mam. Soon I will share details with you mam,2,0.5423
17,05/12/19,2:00 pm,AR❤,I have read the Abstract mam. We can do mam. ...,2,0.0000
18,05/12/19,2:04 pm,Mabel Infoziant,I think Vignesh has the data set will ask him...,0,0.0000
19,05/12/19,2:04 pm,Mabel Infoziant,I have sent the abstracts,4,0.0000
20,05/12/19,2:06 pm,AR❤,Ok mam,1,0.2960
21,05/12/19,2:07 pm,AR❤,I have read both the abstract mam. We can do ...,2,0.0000
22,05/12/19,4:44 pm,Mabel Infoziant,Yes we need to ya about amount and all other ...,0,0.4019
23,05/12/19,4:48 pm,AR❤,Sure mam.,2,0.3182
24,05/12/19,8:07 pm,AR❤,Shall I call mam?,2,0.0000
25,08/12/19,10:45 pm,Mabel Infoziant,Hi I was at church couldn’t take your call,4,0.0000
26,08/12/19,11:52 pm,AR❤,It's k mam,2,0.0000
27,08/12/19,11:55 pm,AR❤,Just to know the tomorrow plan mam.will see t...,3,0.4404
28,09/12/19,12:09 pm,AR❤,Mam can u send Vignesh number??,0,0.1680
29,09/12/19,12:13 pm,Mabel Infoziant,Vignesh ML Infoziant.vcf (file attached),0,0.0000
30,09/12/19,12:23 pm,Mabel Infoziant,I was in a meeting sorry,4,-0.0772
31,09/12/19,12:25 pm,AR❤,Can I cal u mam,2,0.0000
32,09/12/19,12:26 pm,AR❤,Waiting for u r finalization of rates for our...,0,0.0000
33,09/12/19,12:26 pm,AR❤,If we finiliaze I can work with full involvem...,2,0.0000
34,09/12/19,12:28 pm,AR❤,So what ever may be ..if you think your are c...,2,0.5106
35,09/12/19,12:28 pm,AR❤,You deleted this message,0,0.0000
36,09/12/19,12:29 pm,AR❤,Do the needful,0,0.0000
37,09/12/19,12:41 pm,Mabel Infoziant,No ma please hold I am in a hot meeting with ...,4,-0.2960
38,09/12/19,12:42 pm,AR❤,Ok mam thank u,1,0.5719
39,10/12/19,7:59 am,Mabel Infoziant,Ramisha we need to talk today i will call u a...,1,0.0000
40,10/12/19,8:00 am,Mabel Infoziant,Be ready to discuss about the ML titles u have,0,0.3612
41,10/12/19,8:55 am,AR❤,Okay mam,2,0.2263
42,12/12/19,2:26 pm,Mabel Infoziant,ok,1,0.2960
43,15/12/19,8:22 pm,AR❤,Mam are u free?,2,0.5106
44,15/12/19,8:40 pm,Mabel Infoziant,Am at church can call very late or tomorrow only,3,0.0000
45,15/12/19,8:40 pm,AR❤,Kk mam. I will ask Arun brother. Small doubt ...,2,0.5574
46,18/12/19,3:09 pm,AR❤,Hi mam,4,0.0000
47,18/12/19,3:09 pm,AR❤,Any updates mam?,2,0.0000
48,18/12/19,3:11 pm,Mabel Infoziant,U might have to start on the WhatsApp analysis,4,0.0000
49,18/12/19,3:11 pm,Mabel Infoziant,There is one project that got committed,3,0.2732
50,18/12/19,3:12 pm,AR❤,Kk mam👍🏻,2,0.3612

In [14]:
for i, topic in enumerate(nmf_model.components_):
    words = [tfidf.get_feature_names_out()[j] for j in topic.argsort()[-10:]]
    print(f"Topic {i}: {words}")

Topic 0: ['share', 'soon', 'ask', 'yes', 'sure', 'read', 'abstract', 'kk', 'yeah', 'mam']
Topic 1: ['hi', 'kk', 'know', 'meeting', 'yes', 'just', 'send', 'tomorrow', 'mam', 'ok']
Topic 2: ['details', 'abstracts', 'start', 'students', 'phone', 'ask', 'office', 'number', 'vignesh', 'send']
Topic 3: ['ask', 'abstracts', 'number', 'mam', 'office', 'know', 'just', 'tomorrow', 'church', 'hi']
Topic 4: ['students', 'know', 'sure', 'share', 'soon', 'meeting', 'details', 'yes', 'need', 'ramisha']